name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - "*-stable"
  pull_request:
    branches:
      - master
      - main
      - "*-stable"

jobs:
  ci:
    name: "Run Tests (Ruby ${{ matrix.ruby_version }}, Linalg: ${{ matrix.linalg_gem }})"
    runs-on: "ubuntu-latest"
    env:
      # See https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby#matrix-of-gemfiles
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      LINALG_GEM: ${{ matrix.linalg_gem }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "jruby-9.3.4.0"]
        linalg_gem: ["none", "gsl", "numo"]
        # We use `include` to assign the correct Gemfile for each ruby_version
        include:
          - ruby_version: "2.7"
            gemfile: Gemfile
          - ruby_version: "3.0"
            gemfile: Gemfile
          - ruby_version: "3.1"
            gemfile: Gemfile
          - ruby_version: "jruby-9.3.4.0"
            gemfile: Gemfile-jruby
        exclude:
          # Ruby 3.0 does not work with the latest released gsl gem
          # https://github.com/SciRuby/rb-gsl/issues/67
          - ruby_version: "3.0"
            linalg_gem: "gsl"
          # Ruby 3.1 does not work with the latest released gsl gem
          # https://github.com/SciRuby/rb-gsl/issues/67
          - ruby_version: "3.1"
            linalg_gem: "gsl"
          # jruby-9.3.4.0 doesn't easily build the gsl gem on a GitHub worker. Skipping for now.
          - ruby_version: "jruby-9.3.4.0"
            linalg_gem: "gsl"
          # jruby-9.3.4.0 doesn't easily build the numo gems on a GitHub worker. Skipping for now.
          - ruby_version: "jruby-9.3.4.0"
            linalg_gem: "numo"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Lapack
        if: ${{ matrix.linalg_gem == 'numo' }}
        run: sudo apt-get install -y liblapacke-dev libopenblas-dev
      - name: "Set up ${{ matrix.label }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run Minitest based tests
        run: script/test

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
